import jsPDF from "jspdf";
import "jspdf-autotable";

export function generateReportPDF({
  student,
  results,
  overallGPA,
  sessionName,
  termName,
}) {
  const doc = new jsPDF();

  // Header
  doc.setFontSize(16);
  doc.text("SchoolHub Report Card", 14, 15);

  doc.setFontSize(11);
  doc.text(`Name: ${student.name}`, 14, 25);
  doc.text(`Class: ${student.class}`, 14, 32);
  doc.text(`Session: ${sessionName}`, 14, 39);
  doc.text(`Term: ${termName}`, 14, 46);
  doc.text(`Overall GPA: ${overallGPA.toFixed(2)}`, 14, 53);

  // Table
  doc.autoTable({
    startY: 60,
    head: [["Subject", "Score", "GPA", "Remark"]],
    body: results.map(r => [
      r.subject,
      r.averageScore,
      r.gpa,
      r.remark,
    ]),
  });

  // Footer
  doc.text(
    "Generated by SchoolHub",
    14,
    doc.internal.pageSize.height - 10
  );

  doc.save(`${student.name}_report_card.pdf`);
}
